name: qGP-WitherTrust
version: '${project.version}'
main: gg.quartzdev.qgpwithertrust.qGPWitherTrust
api-version: '1.20'
dependencies:
  server:
    GriefPrevention:
      load: AFTER
      required: true
