name: Create Plugin.jar

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: |
        artifactPath="$(pwd)/target"
        artifactName="$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)"
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "artifactPath=${artifactPath}" >> $GITHUB_ENV
        echo "artifactName=${artifactName}" >> $GITHUB_ENV
        echo git_hash=${git_hash} >> $GITHUB_ENV
        mvn clean package
        mv "${artifactPath}/${artifactName}.jar" "${artifactPath}/${artifactName}-${git_hash}.jar"
        
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifactName }}-${{ env.git_hash }}.jar
        path: ${{ env.artifactPath }}/${{ env.artifactName }}-${{ env.git_hash }}.jar
